### ISSUE TITLE
Posibilidad (funcion requerida.)

### ISSUE THREAD

**Issue by dinobossytnew** [Ajneb97/PlayerKits2#19]
añadir a inventory.yml la posibilidad de lores en los items algo por el estilo de ejemplo: 
```
inventories:
  main_inventory:
    slots: 53
    title: "&8✺ &7Menu de Kits [1/3]"
    10;11;13;14;15;16:
      item:
        id: "BLACK_STAINED_GLASS_PANE"
        name: "&8⬆ &7Categorias"
        lore: 
        - "&8⬇ &7Opciones"
```
